s1={"apple","mango","dragonfruit",1,2}
s2={"mango",2,"papaya"}
s1.add("Fruit")
print(s1)
s1.remove("mango")
print(s1)
s1.discard("papaya")
print(s1)
print(s1|s2)
print(s2|s1)
print(s1&s2)
print(s1-s2)
print(s2-s1)
